-- MySQL Script generated by MySQL Workbench
-- Mon Jan  4 23:53:48 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bdlosMichis
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdlosMichis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdlosMichis` DEFAULT CHARACTER SET utf8 ;
USE `bdlosMichis` ;

-- -----------------------------------------------------
-- Table `bdlosMichis`.`duenio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdlosMichis`.`duenio` (
  `idduenio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `apellidop` VARCHAR(50) NOT NULL,
  `apellidom` VARCHAR(50) NOT NULL,
  `telefono` VARCHAR(10) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idduenio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdlosMichis`.`tipoAnimal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdlosMichis`.`tipoAnimal` (
  `idtipoAnimal` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(256) NULL,
  PRIMARY KEY (`idtipoAnimal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdlosMichis`.`veterinario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdlosMichis`.`veterinario` (
  `idveterinario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `apellidop` VARCHAR(50) NOT NULL,
  `apellidom` VARCHAR(50) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(10) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `estado` TINYINT NOT NULL,
  PRIMARY KEY (`idveterinario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdlosMichis`.`diagnostico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdlosMichis`.`diagnostico` (
  `iddiagnostico` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `tratamiento` VARCHAR(256) NULL,
  PRIMARY KEY (`iddiagnostico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdlosMichis`.`consultorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdlosMichis`.`consultorio` (
  `idconsultorio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idconsultorio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdlosMichis`.`animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdlosMichis`.`animal` (
  `idanimal` INT NOT NULL AUTO_INCREMENT,
  `alias` VARCHAR(45) NULL,
  `idtipoAnimal` INT NOT NULL,
  `idduenio` INT NOT NULL,
  `edad` VARCHAR(20) NULL,
  `peso` VARCHAR(10) NULL,
  `sexo` TINYINT NOT NULL,
  PRIMARY KEY (`idanimal`),
  INDEX `fk_duenio_animal_idx` (`idduenio`),
  INDEX `fk_tipo_animal_idx` (`idtipoAnimal`),
  CONSTRAINT `fk_duenio_animal`
    FOREIGN KEY (`idduenio`)
    REFERENCES `bdlosMichis`.`duenio` (`idduenio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tipo_animal`
    FOREIGN KEY (`idtipoAnimal`)
    REFERENCES `bdlosMichis`.`tipoAnimal` (`idtipoAnimal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdlosMichis`.`visita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdlosMichis`.`visita` (
  `idvisita` INT NOT NULL AUTO_INCREMENT,
  `idAnimal` INT NOT NULL,
  `idVeterinario` INT NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  `idConsultorio` INT NOT NULL,
  PRIMARY KEY (`idvisita`),
  INDEX `fk_animal_visita_idx` (`idAnimal`),
  INDEX `fk_veterinario_animal_idx` (`idVeterinario`),
  INDEX `fk_consultorio_visita_idx` (`idConsultorio`),
  CONSTRAINT `fk_animal_visita`
    FOREIGN KEY (`idAnimal`)
    REFERENCES `bdlosMichis`.`animal` (`idanimal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_veterinario_visita`
    FOREIGN KEY (`idVeterinario`)
    REFERENCES `bdlosMichis`.`veterinario` (`idveterinario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consultorio_visita`
    FOREIGN KEY (`idConsultorio`)
    REFERENCES `bdlosMichis`.`consultorio` (`idconsultorio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdlosMichis`.`detalleVisita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdlosMichis`.`detalleVisita` (
  `iddetalleVisita` INT NOT NULL AUTO_INCREMENT,
  `idVisita` INT NOT NULL,
  `tipoConsulta` VARCHAR(45) NOT NULL,
  `idDiagnostico` INT NOT NULL,
  PRIMARY KEY (`iddetalleVisita`),
  INDEX `fk_visita_detalle_idx` (`idVisita`),
  INDEX `fk_diagnostico_detalle_idx` (`idDiagnostico`),
  CONSTRAINT `fk_visita_detalle`
    FOREIGN KEY (`idVisita`)
    REFERENCES `bdlosMichis`.`visita` (`idvisita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_diagnostico_detalle`
    FOREIGN KEY (`idDiagnostico`)
    REFERENCES `bdlosMichis`.`diagnostico` (`iddiagnostico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdlosMichis`.`cita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdlosMichis`.`cita` (
  `idcita` INT NOT NULL AUTO_INCREMENT,
  `idAnimal` INT NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  `estado` VARCHAR(10) NOT NULL,
  `idConsultorio` INT NOT NULL,
  PRIMARY KEY (`idcita`),
  INDEX `fk_animal_cita_idx` (`idAnimal`),
  INDEX `fk_consultorio_cita_idx` (`idConsultorio`),
  CONSTRAINT `fk_animal_cita`
    FOREIGN KEY (`idAnimal`)
    REFERENCES `bdlosMichis`.`animal` (`idanimal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consultorio_cita`
    FOREIGN KEY (`idConsultorio`)
    REFERENCES `bdlosMichis`.`consultorio` (`idconsultorio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
